[build-system]
requires = ["setuptools", "wheel", "torch"]

[tool.black]
safe = true
line-length = 88

[tool.usort]
first_party_detection = false
target-version = ["py38"]
excludes = [
    "gallery",
    "tutorials",
]
