# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

def unravel_key_list(list_of_keys): ...
def unravel_keys(keys): ...
def unravel_key(key): ...
def _unravel_key_to_tuple(key): ...
