name: Unit-tests on MacOS

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

env:
  CHANNEL: "nightly"

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  tests-intel:
    strategy:
      matrix:
        python_version: ["3.8", "3.11"]
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/macos_job.yml@main
    with:
      repository: pytorch/tensordict
      timeout: 120
      script: |
        # Set env vars from matrix
        set -e
        set -v
        export PYTHON_VERSION=${{ matrix.python_version }}
        export CU_VERSION="cpu"
        export SYSTEM_VERSION_COMPAT=0
        export TORCH_VERSION=nightly
        export ARCH=x86_64

        echo "PYTHON_VERSION: $PYTHON_VERSION"
        echo "CU_VERSION: $CU_VERSION"

        ## setup_env.sh
        bash .github/unittest/linux/scripts/setup_env.sh
        bash .github/unittest/linux/scripts/install.sh
        bash .github/unittest/linux/scripts/run_test.sh
        bash .github/unittest/linux/scripts/post_process.sh

  tests-silicon:
    strategy:
      matrix:
        python_version: ["3.9"]
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/macos_job.yml@main
    with:
      runner: macos-m1-12
      repository: pytorch/tensordict
      timeout: 120
      script: |
        # Set env vars from matrix
        set -e
        set -v
        export PYTHON_VERSION=${{ matrix.python_version }}
        export CU_VERSION="cpu"
        export SYSTEM_VERSION_COMPAT=0
        export TORCH_VERSION=nightly
        export ARCH=arm64

        echo "PYTHON_VERSION: $PYTHON_VERSION"
        echo "CU_VERSION: $CU_VERSION"

        ## setup_env.sh
        bash .github/unittest/linux/scripts/setup_env.sh
        bash .github/unittest/linux/scripts/install.sh
        bash .github/unittest/linux/scripts/run_test.sh
        bash .github/unittest/linux/scripts/post_process.sh
